### ISSUE TITLE
first push will fail

### ISSUE THREAD

**Issue by darrencoen** [dotsunited/docker-git-ftp#2]
hi! thanks for making this docker image but the first push will fail because the server doesn't have the "last deployed" information from the file not-yet-created on the server.

typically you would first do a ```git ftp init``` but instead you can incorporate a flag ```--auto-init``` in the push command

your config example script should be:

```git ftp push -v --auto-init --syncroot public/ --user $FTP_DEPLOY_USER --passwd $FTP_DEPLOY_PASSWORD $FTP_DEPLOY_HOST```

from the documentation: https://github.com/git-ftp/git-ftp/blob/master/man/git-ftp.1.md

thanks!

**Comment by nebuIr** [comment]
Hi! Thank you for bringing this to our attention!

We already use `--auto-init` in our setups, but we hadn't yet updated the readme here to reflect this change.
I've now updated it accordingly in af7943d8 👍

Thanks again 😀
